ARG BASE_IMAGE=node:20.3.1-bullseye-slim
FROM ${BASE_IMAGE}

ARG PROJECT_NAME=wordapp-frontend
ARG APPLICATION_DIRECTORY=/home/node/${PROJECT_NAME}
ARG FRONTEND_WEB_PATH=applications/frontend

ENV DEBIAN_FRONTEND="noninteractive" \
    LC_ALL="C.UTF-8" \
    LANG="C.UTF-8"

RUN apt update \
    && apt install --no-install-recommends -y git curl make

WORKDIR ${APPLICATION_DIRECTORY}