version: "3.8"

services:
  backend:
    build:
      args:
        - RUN_POETRY_INSTALL_AT_BUILD_TIME=true
      context: ../../
      dockerfile: environments/Dockerfile.backend
    tty: true
    volumes:
        - ../../:/home/trailblazer/wordapp-backend
