name: dev-wordapp
services:
  backend:
    build:
      target: base
      args:
        - BASE_IMAGE=python:3.11.13-slim-bookworm
        - PROJECT_NAME=wordapp
        - SERVICE_NAME=backend
        - USER_NAME=developer
        - GROUP_NAME=developers
        - UID=1000
        - GID=1000
      context: ../../applications/backend
      dockerfile: environments/Dockerfile.backend
    env_file:
      - ../../applications/backend/environments/backend.env
    tty: true
    init: true
    volumes:
      - ../../applications/backend:/home/developer/wordapp-backend
    ports:
      - 8000:8000

  frontend:
    build:
      target: base
      args:
        - BASE_IMAGE=node:22.16.0-bookworm-slim
        - PROJECT_NAME=wordapp
        - SERVICE_NAME=frontend
        - USER_NAME=developer
        - GROUP_NAME=developers
        - UID=1000
        - GID=1000
        - RUN_YARN_INSTALL_AT_BUILD_TIME=true
      context: ../../applications/frontend
      dockerfile: environments/Dockerfile.frontend
    env_file:
      - ../../applications/frontend/environments/frontend.env
    tty: true
    init: true
    volumes:
      - ../../applications/frontend:/home/developer/wordapp-frontend
    ports:
      - 4173:4173
      - 5173:5173