name: tests
on: [pull_request]

env:
  DOCKER_FILE_DIRECTORY: environments
  DOCKER_COMPOSE_DIRECTORY: environments/ci

jobs:
  lint-and-test:
    name: ${{ matrix.os }} / ${{ matrix.python-version }}
    runs-on: ${{ matrix.image }}
    environment:
      name: development
    env:
      POSTGRES_DB: wordapp
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      FIRST_SUPERUSER: ${{ secrets.FIRST_SUPERUSER }}
      FIRST_SUPERUSER_EMAIL: ${{ secrets.FIRST_SUPERUSER_EMAIL }}
      FIRST_SUPERUSER_PASSWORD: ${{ secrets.FIRST_SUPERUSER_PASSWORD }}

    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu]
        python-version: ["3.10"]
        include:
          - os: ubuntu
            image: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Check version info
        run: pwd && docker compose --version && docker --version

      - name: Create and start docker container
        run: docker compose up -d
        working-directory: ${{ env.DOCKER_COMPOSE_DIRECTORY }}

      # pytest-cov export coverage data to a file
      # However, the directory made by actions/checkout does not allow write
      # chmod is needed to resolve above problem
      - name: Change permission
        run: chmod 777 ./applications/backend

      - name: Wait for PostgreSQL to become available
        run: |
          until docker compose exec -T postgresql pg_isready -U ${{ env:POSTGRES_USER }}; do
            echo 'Waiting for PostgreSQL...'
            sleep 3
          done
        working-directory: ${{ env.DOCKER_COMPOSE_DIRECTORY }}

      - name: Make test schema in database
        run: docker compose exec -T postgresql psql -U ${{ env:POSTGRES_USER }} -d ${{ env:POSTGRES_DB }} -c "CREATE SCHEMA test;"
        working-directory: ${{ env.DOCKER_COMPOSE_DIRECTORY }}

      # In the built stage of Docker image, .venv dir is moved from working directory to prevent
      # overwrite by volume operation of Docker. Here, .venv is moved back to working directory.
      - name: Move back the .venv directory
        run: docker compose exec -T backend mv ../.venv .
        working-directory: ${{ env.DOCKER_COMPOSE_DIRECTORY }}

      - name: Run lint
        run: docker compose exec -T backend make lint
        working-directory: ${{ env.DOCKER_COMPOSE_DIRECTORY }}

      - name: Run test code
        run: docker compose exec -T backend make test
        working-directory: ${{ env.DOCKER_COMPOSE_DIRECTORY }}